apiVersion: projectcalico.org/v3
kind: Node
metadata:
  annotations:
    projectcalico.org/kube-labels: '{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"clab-bgp-cplane-demo-worker2","kubernetes.io/os":"linux","rack":"rack2"}'
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: clab-bgp-cplane-demo-worker2
    kubernetes.io/os: linux
    rack: rack2
  name: clab-bgp-cplane-demo-worker2
spec:
  addresses:
  - address: 192.168.8.10/24
    type: CalicoNodeIP
  - address: 172.19.0.5
    type: InternalIP
  bgp:
    asNumber: 65008
    ipv4Address: 192.168.8.10/24
  orchRefs:
  - nodeName: clab-bgp-cplane-demo-worker2
    orchestrator: k8s
status:
  podCIDRs:
  - 10.244.2.0/24
